### ISSUE TITLE
White background doenst work well with the text

### ISSUE THREAD

**Issue by JesperKuipers** [Naamloos/FeestSpel#5]
White background doenst well with the text
![image](https://user-images.githubusercontent.com/44586411/117131972-7a1d9b80-ada2-11eb-9e3f-423ad04dd18d.png)

**Comment by Naamloos** [comment]
Proposed fix: either implement a treshold for values, or pick colors from a preset list.

**Comment by Naamloos** [comment]
fixed in da9c789
